[project]
name = "todo-tui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "textual>=0.73.0",
    "textual-dev>=1.6.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
